## Questions

* How to effectively put a prediction interval around the median Lifetime Rental Count? 
* Should PI/CI be continually recalculated using the new "population data" or could this possibly conceal a trend over time? 

[CI Resource](https://onlinecourses.science.psu.edu/stat414/node/261)
[PI Resource](http://www.propharmagroup.com/blog/understanding-statistical-intervals-part-2-prediction-intervals/)

In [31]:
import pandas as pd
import datetime
import math

In [45]:
mdrDat_init = pd.read_csv('sql_runner_MDRS_2018-04-25.csv')
mdrDat_init['MoYr'] = pd.to_datetime(mdrDat_init['start_time']).apply(lambda x: str(x.month) + '-'+str(x.year))
mdrDat_init['WkYr'] = pd.to_datetime(mdrDat_init['start_time']).apply(lambda x: str(str(x.year)+'-'+ str(x.isocalendar()[1])))
mdrDat_init.columns

Index(['rentalid', 'accountid', 'accounttype', 'subscriptionid',
       'subscriptiontypegroup', 'discpartner', 'rentalaccessmethod',
       'countrentals', 'bikedisplay', 'bikeid', 'startstation_id',
       'rental_status', 'start_time', 'end_time', 'calcend_time',
       'nextdockerror_ts', 'minbiid', 'minbibid', 'minbirid', 'minbikeintime',
       'MoYr', 'WkYr'],
      dtype='object')

In [49]:
mdrDat_init['WkYr'].value_counts().median()

89.0

In [78]:
results = []

for loop in range(1000):
    sample = mdrDat_init.sample(n=89, axis=0)
    medianRidesb4MDR = sample['countrentals'].median()
    stdRidesb4MDR = sample['countrentals'].std()
    results.append([loop, medianRidesb4MDR, stdRidesb4MDR])

medianRideSampels = pd.DataFrame(results)
medianRideSampels.columns = ['Loop', 'Median', 'Stdev']
medianRideSampels

      Loop  Median        Stdev
0        0     3.0   266.569817
1        1     4.0   217.963518
2        2     7.0   335.378065
3        3    22.0  9273.226534
4        4    19.0   292.310965
5        5    12.0   244.635526
6        6     5.0   255.995164
7        7     7.0   265.011010
8        8     9.0   379.701761
9        9    23.0   528.258552
10      10    11.0   271.181506
11      11    14.0   445.842254
12      12    11.0   309.274820
13      13     5.0   456.059122
14      14    19.0   288.613291
15      15    15.0   268.606547
16      16    13.0   279.729567
17      17    19.0   373.036665
18      18     5.0   375.743116
19      19    10.0   275.480902
20      20     8.0   377.270394
21      21    13.0   359.898439
22      22    14.0   411.665435
23      23    12.0   315.292609
24      24    12.0   183.096659
25      25     9.0   365.034436
26      26     7.0   233.831534
27      27     6.0   238.429157
28      28    36.0   241.255297
29      29    13.0   347.986539
...    ...     ...          ...
9970  9970    23.0   361.282998
9971  9971    14.0   310.120252
9972  9972    11.0   386.617535
9973  9973    16.0   394.885612
9974  9974     8.0   359.582979
9975  9975     8.0   383.510295
9976  9976    18.0   292.017975
9977  9977    18.0   365.607402
9978  9978     9.0  1260.831997
9979  9979     9.0   417.940061
9980  9980    13.0  3959.217001
9981  9981     7.0   198.079546
9982  9982    20.0   264.968773
9983  9983     9.0   277.572346
9984  9984    12.0   361.212744
9985  9985    31.0   304.728366
9986  9986     7.0   340.132447
9987  9987    45.0   462.159909
9988  9988    25.0   258.442204
9989  9989    41.0   454.410509
9990  9990    28.0  9275.191992
9991  9991    13.0   255.331281
9992  9992     9.0   342.330976
9993  9993     7.0   531.230123
9994  9994    12.0   346.148405
9995  9995     7.0   252.064575
9996  9996     9.0   299.312341
9997  9997    22.0   395.670748
9998  9998    17.0   451.865251
9999  9999     8.0  3787.945904

[10000 rows x 3 columns]

In [79]:
def calcPI(medianSampleSeries):
    """ t value 1.96 is used for t.95; can be adjusted """
    stdv = medianSampleSeries.std()
    n = len(medianSampleSeries)
    POPmedian = medianSampleSeries.median()
    CI95 = POPmedian + 2.04227*(stdv*math.sqrt(1 + 1/n))
    CI05 = POPmedian - 2.04227*(stdv*math.sqrt(1 + 1/n))
    
    return (CI05, CI95)

In [80]:
# this looks roughly like it's working 
CIs = calcPI(medianRideSampels['Median'])
CIs

(-8.61341776643161, 30.61341776643161)

In [81]:
withinPI = medianRideSampels[(medianRideSampels['Median'] >= CIs[0]) & (medianRideSampels['Median'] <= CIs[1])]
withinPI.shape[0]/medianRideSampels.shape[0]

0.9344

old

In [ ]:
def ltTen(val):
    if val <= 10:
        yn = 1
    elif val > 10:
        yn = 0
    return yn

fullMDR_dat['CountRentals'].apply(lambda x: ltTen(x)).value_counts()

In [ ]:
def calcRentalCountCI(medianSampleSeries):
    """ t value 1.96 is used for t.95; can be adjusted """
    stdv = medianSampleSeries.std()
    n = len(medianSampleSeries)
    POPmedian = medianSampleSeries.median()
    CI95 = POPmedian + 1.96*(stdv/math.sqrt(n))
    CI05 = POPmedian - 1.96*(stdv/math.sqrt(n))
    
    return (CI05, CI95)