In [1]:
import pandas as pd

Ideas for processing MIT Airline Data Project data:
* Could be done as a class that processes the SEC data spreadsheet and returns an object where you can call different parts of the spreadsheet
* look for places where the data has already been processed into easier to handle 



http://web.mit.edu/airlinedata/www/Revenue&Related.html

In [3]:

jetblueProfit_dat =  pd.read_excel('JetBlue Airways Corp.xls', sheet_name='Sheet1', header=1)
jetblueProfit_dat

,All units in Millions or Millions USD,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Income Statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Passenger Revenue,102.000,310.000,615.000,965.000,1220.000,1620.000,2223.000,2636.000,3056.00,2928.00,3412.000,4080.00,4550.000,4971.000,5343.000,5893.000,6013.000
2,Regional Affiliate Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Total Revenue,105.000,321.000,635.000,998.000,1265.000,1701.000,2363.000,2842.000,3388.00,3286.00,3779.000,4504.00,4982.000,5441.000,5817.000,6416.000,6632.000
4,Wages Salaries & Benefits,33.000,85.000,162.000,267.000,337.000,428.000,553.000,648.000,694.00,776.00,891.000,947.00,1044.000,1135.000,1294.000,1540.000,1698.000
5,Aircraft Fuel Expense,18.000,42.000,76.000,147.000,255.000,488.000,752.000,929.000,1352.00,945.00,1115.000,1664.00,1806.000,1899.000,1912.000,1348.000,1074.000
6,Depreciation & Amortization,4.000,10.000,27.000,51.000,77.000,115.000,151.000,176.000,205.00,228.00,220.000,233.00,258.000,290.000,320.000,345.000,393.000
7,Net Interest Expense,4.000,12.000,16.000,21.000,45.000,88.000,145.000,171.000,237.00,187.00,176.000,-184.00,175.000,162.000,147.000,127.000,104.000
8,Operating Expense,126.000,294.000,530.000,831.000,1154.000,1653.000,2236.000,2673.000,3279.00,3007.00,3446.000,4182.00,4606.000,5013.000,5302.000,5200.000,5320.000
9,Operating Income (Loss),-21.000,27.000,105.000,167.000,111.000,48.000,127.000,169.000,109.00,279.00,333.000,322.00,376.000,428.000,515.000,1216.000,1312.000
10,Pretax Income (Loss),-22.000,42.000,95.000,174.000,75.000,-24.000,9.000,41.000,-76.00,99.00,161.000,145.00,209.000,279.000,623.000,1097.000,1216.000
11,Net Income (Loss),-21.000,39.000,55.000,103.000,46.000,-20.000,-1.000,18.000,-76.00,58.00,97.000,86.00,128.000,168.000,401.000,677.000,759.000
12,Balance Sheet Asset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Cash & Short-term Investment,34.000,118.000,258.000,608.000,450.000,484.000,699.000,834.000,571.00,1136.00,960.000,1206.00,731.000,627.000,708.000,876.000,971.000
14,Restricted Cash & Short-term Investments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Total Current Assets,0.000,144.000,283.000,646.000,514.000,635.000,927.000,1116.000,962.00,1538.00,1360.000,1628.00,1100.000,1056.000,1200.000,1373.000,1567.000
16,Total Assets,344.000,674.000,1379.000,2185.000,2797.000,3892.000,4843.000,5598.000,6023.00,6554.00,6593.000,7071.00,7070.000,7350.000,7839.000,8644.000,9487.000
17,Balance Sheet Liabilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Air Traffic Liability,0.000,52.000,96.000,135.000,174.000,243.000,340.000,426.000,445.00,455.00,514.000,627.00,693.000,825.000,973.000,1053.000,1120.000
19,Current Liability,0.000,194.000,270.000,370.000,488.000,676.000,854.000,1256.000,1081.00,1169.00,1093.000,1412.00,1608.000,1874.000,1936.000,2275.000,2223.000
20,"Long-term Debt & Capital Lease Obligations, Le...",0.000,0.000,639.000,1012.000,1396.000,2103.000,2626.000,2588.000,2883.00,2920.00,2850.000,2850.00,2457.000,2116.000,1968.000,1379.000,1195.000
21,Pension & Post Retirement Benefits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Retained Earnings (Accumulated deficit),0.000,-33.000,16.000,120.000,165.000,145.000,144.000,162.000,86.00,118.00,219.000,305.00,433.000,601.000,1002.000,1679.000,2446.000
23,Total Stockholder Equity (deficit),0.000,-32.000,415.000,670.000,754.000,911.000,952.000,1036.000,1261.00,1539.00,1654.000,1757.00,1888.000,2134.000,2529.000,3210.000,4013.000
24,Cash Flow Statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Net Cash Provided by (Used in) Operating Activity,3.000,111.000,217.000,287.000,199.000,170.000,274.000,358.000,-17.00,486.00,523.000,614.00,698.000,758.000,912.000,1598.000,1632.000
26,Net Cash Provided by (Used in) Investing Activ...,-241.000,-365.000,-880.000,-987.000,-720.000,-1276.000,-1307.000,-734.000,-247.00,-457.00,-696.000,-502.00,-867.000,-476.000,-379.000,-1134.000,-1045.000
27,Net Cash Provided by (Used in) Financing activ...,254.000,262.000,657.000,789.000,437.000,1093.000,1037.000,556.000,635.00,306.00,-258.000,96.00,-322.000,-239.000,-417.000,-487.000,-472.000
28,Payments on Long-term Debt and Capital Lease O...,-19.000,-35.000,-71.000,-57.000,-77.000,-117.000,-390.000,-265.000,-673.00,-180.00,-333.000,-238.00,-418.000,-612.000,-702.000,-328.000,-368.000
29,Proceeds from Issuance of Long-term Debt,138.000,185.000,416.000,446.000,499.000,872.000,855.000,376.000,716.00,446.00,116.000,245.00,215.000,393.000,342.000,0.000,0.000
30,Net Increase (Decrease) in Cash,16.000,83.000,129.000,89.000,-84.000,-13.000,4.000,180.000,371.00,335.00,-431.000,208.00,-491.000,43.000,116.000,-23.000,115.000
31,Operating Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Regional Passengers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Regional ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Regional RPM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Mainline Passengers,0.003,3.117,5.752,9.012,11.783,14.729,18.565,21.387,21.92,22.45,24.254,26.37,28.956,30.463,32.078,35.101,38.263
36,Mainline ASM,1372.000,4208.000,8240.000,13639.000,18911.000,23703.000,28594.000,31904.000,32442.00,32558.00,34744.000,37232.00,40075.000,42824.000,44994.000,49258.000,53620.000
37,Mainline RPM,1004.000,3282.000,6836.000,11527.000,15730.000,20200.000,23320.000,25737.000,26071.00,25955.00,28279.000,30698.00,33563.000,35836.000,37813.000,41711.000,45619.000
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Data Source: SEC 10K Filings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# create column names for income statement DF 
indexTry = list(jetblueProfit_dat.columns[1:])
indexTry.insert(0,jetblueProfit_dat.iloc[0,0])